# Stage 1: Build PHP dependencies
FROM composer:2 AS composer_build

# Stage 2: Build the PHP-FPM application image
FROM php:8.4-fpm-alpine

COPY --from=composer_build /usr/bin/composer /usr/local/bin/composer

RUN apk add $PHPIZE_DEPS

RUN wget https://github.com/php/pie/releases/latest/download/pie.phar
RUN chmod +x pie.phar
RUN mv pie.phar /usr/local/bin/pie
RUN pie install open-telemetry/ext-opentelemetry
RUN pie install solarwinds/apm_ext

# Append the new limit to the official image's override file
RUN echo 'pm.max_children = 20' >> /usr/local/etc/php-fpm.d/zz-docker.conf
RUN echo 'pm.start_servers = 8' >> /usr/local/etc/php-fpm.d/zz-docker.conf
RUN echo 'pm.min_spare_servers = 1' >> /usr/local/etc/php-fpm.d/zz-docker.conf
RUN echo 'pm.max_spare_servers = 15' >> /usr/local/etc/php-fpm.d/zz-docker.conf

WORKDIR /var/www/html

# Copy application code
COPY index.php .
COPY composer-apm-php-9-alpha.json ./composer.json

RUN composer install

# Expose port for PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]
