# Stage 1: Build PHP dependencies
FROM composer:2 AS composer_build

# Stage 2: Build the PHP-FPM application image
FROM php:8.4-fpm-alpine

COPY --from=composer_build /usr/bin/composer /usr/local/bin/composer

WORKDIR /var/www/html

# Copy application code
COPY index.php .
COPY composer-uninstrumented.json ./composer.json

RUN composer install

# Expose port for PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]
